import type { Metadata } from "next";

import "./globals.css";
import localFont from "next/font/local"
import { LanguageProvider } from "@/context/useLanguage";

const articulat = localFont({
  src: [
    {
      path: "../fonts/ArticulatCF-Medium.otf",
      weight: "600",
      style: "medium"
    },
    {
      path: "../fonts/ArticulatCF-Normal.otf",
      weight: "500",
      style: "normal"
    }
  ],
  preload: true,
  variable: "--font-articulat"
})


export const metadata: Metadata = {
  title: "Moises",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${articulat.variable}`}>
      <body>
        <LanguageProvider>
          {children}
        </LanguageProvider>
      </body>
    </html>
  );
}
